"""В employee добавлено поле is_online

Revision ID: 00909c828969
Revises: 4419c4ddab26
Create Date: 2026-04-24 14:10:56.352432

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00909c828969'
down_revision = '4419c4ddab26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_online', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.drop_column('is_online')

    # ### end Alembic commands ###
