"""add report fields to task

Revision ID: 51e7f7577cef
Revises: 6420302b208d
Create Date: 2026-04-26 16:37:50.776644

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51e7f7577cef'
down_revision = '6420302b208d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('report_text', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('report_files', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_column('report_files')
        batch_op.drop_column('report_text')

    # ### end Alembic commands ###
