"""Удалено is_online поле

Revision ID: b224ad395341
Revises: 00909c828969
Create Date: 2026-04-24 14:54:01.611637

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b224ad395341'
down_revision = '00909c828969'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.drop_column('is_online')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_online', sa.BOOLEAN(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
